baseURL = "/"
copyright = "© 2017- <a href=\"https://babibubebo.org/about/profile/\">Babibubebon</a></a> - <a href=\"https://babibubebo.org/about/site_about/\">Terms and Privacy</a>"
languageCode = "ja-jp"
theme = "hugo-theme-basic"
title = "Metadata.Moe"

enableEmoji = false
googleAnalytics = "UA-7878096-15"

[params]
description = "メタデータを愛でる人々のためのWebサイトです。"
titleLogo = "<img src=\"/img/logo.svg\" width=\"48\" height=\"48\">"

[[params.menu]]
description = "アニメ作品のデータベース"
name = "あにむめも"
url = "https://animedb.moe/"
category = "dataset"

[[params.menu]]
description = "とあるシリーズのデータセットとSPARQLエンドポイント"
name = "とあるSPARQL"
url = "toaru-sparql/"
category = "dataset"

[[params.menu]]
description = "メディア芸術データベース(ベータ版)のLODデータセットとSPARQLエンドポイント"
name = "メディア芸術データベース LOD"
url = "project/madb/lod/"
category = "dataset"

[[params.menu]]
description = "DBpedia JapaneseのSPARQLエンドポイント(Apache Jena Fuseki)"
name = "DBpedia Japanese mirror"
url = "project/dbpedia-ja/"
category = "dataset"

[[params.menu]]
description = "ヲタクコンテンツのメタデータを探究する"
name = "Otaku Metadata Research"
url = "project/research/"
category = "project"

[[params.menu]]
description = "RDF問い合わせ言語SPARQLに萌える話"
name = "SPARQL萌え"
url = "project/sparql/"
category = "project"

[[params.menu]]
description = "メタデータに萌える人々のためのFediverseインスタンス"
name = "Social.Metadata.Moe"
url = "project/fediverse/"
category = "project"

[[params.menu]]
name = "MADB 地下実験室"
description = "メディア芸術データベースで遊ぶ"
url = "project/madb/"
category = "project"

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

[markup.goldmark.renderer]
unsafe = true
