baseURL = "https://metadata.moe/"
copyright = "© 2020 <a href=\"https://babibubebo.org/about/profile/\">Babibubebon</a></a> - <a href=\"https://babibubebo.org/about/site_about/\">Terms and Privacy</a>"
languageCode = "ja-jp"
theme = "hugo-theme-basic"
title = "Metadata.Moe"

enableEmoji = false
googleAnalytics = "UA-7878096-15"

[params]
description = "メタデータを愛でる人々のためのWebサイトです。"
titleLogo = "<img src=\"/img/logo.svg\" width=\"48\" height=\"48\">"
twitter = "bbbbbo_n"

[[params.menu]]
description = "アニメ作品のデータベース "
name = "あにむめも"
url = "https://animedb.moe/"

[[params.menu]]
description = "とあるシリーズのデータセットとSPARQLエンドポイント"
name = "とあるSPARQL"
url = "toaru-sparql/"

[[params.menu]]
description = "メディア芸術データベース(ベータ版)のデータをRDFに変換したデータセット・SPARQLエンドポイント"
name = "メディア芸術データベース LOD"
url = "project/madb-lod/"

[[params.menu]]
description = "DBpedia JapaneseのSPARQLエンドポイント(Apache Jena Fuseki)"
name = "DBpedia Japanese mirror"
url = "project/dbpedia-ja/"

[[params.menu]]
description = "アニメ作品のメタデータを追求する"
name = "AniMetadata Research"
url = "project/animetadata/"

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

[markup.goldmark.renderer]
unsafe = true
